CREATE TABLE IF NOT EXISTS USER (
    ID_USER INTEGER NOT NULL PRIMARY KEY,
    USERNAME VARCHAR2(10) NOT NULL,
    PASS VARCHAR2(10) NOT NULL,
    NAME VARCHAR2(10),
    SURNAME1 VARCHAR2(10),
    SURNAME2 VARCHAR2(10)
);

INSERT INTO USER (ID_USER, USERNAME, PASS, NAME, SURNAME1, SURNAME2) VALUES (1, 'pepe','pepep','Pepe','Pepea1','Pepea2');
INSERT INTO USER (ID_USER, USERNAME, PASS, NAME, SURNAME1, SURNAME2) VALUES (2, 'ana','anap','Ana','Anaa1','Anaa2');
INSERT INTO USER (ID_USER, USERNAME, PASS, NAME, SURNAME1, SURNAME2) VALUES (3, 'gato','gatop','Gato','Gatoa1','Gatoa2');